project_id = "fjpunfvhezivlhyrnyym"

[auth]
site_url = "https://mirghaniya.vercel.app"
additional_redirect_urls = ["https://mirghaniyasupercentre.lovable.app", "https://mirghaniya.vercel.app"]

[functions.send-order-notification]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-manage-role]
verify_jwt = false

[functions.verify-old-password]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.sitemap]
verify_jwt = false